site_name: Linux Documentation
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - search
  - mermaid2

nav:
  - INFO: index.md
  - Linux:
    - Archive: 'linux/archive.md'
    - Commands: 'linux/commands.md'
    - Crontab: 'linux/crontab.md'
    - HTTP CRUD: 'linux/HTTP_CRUD.md'
    - Env Var: 'linux/env_var.md'
    - Filter: 'linux/filter.md'
    - Path: 'linux/path.md'
    - Permission: 'linux/permission.md'
    - File System: 'linux/file_system.md'
    - Services: 'linux/services.md'
    - User: 'linux/user.md'
    - Vim: 'linux/vim.md'
    - GUI: 'linux/GUI.md'
    - Distros: 'linux/distros.md'
    - Boot: 'linux/boot.md'
    - Kernel: 'linux/kernel.md'
  - Networking:
    - OSI: 'networking/OSI.md'