site_name: Technology Documentation
site_author: Alexander Lindholm
site_url: https://docs.alexanderlindholm.net
repo_url: https://github.com/Alex0424/docs

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - INFO: index.md

  - Linux:
    - INFO: linux/index.md
    - Archive: 'linux/archive.md'
    - Commands: 'linux/commands.md'
    - Crontab: 'linux/crontab.md'
    - HTTP CRUD: 'linux/HTTP_CRUD.md'
    - Env Var: 'linux/env_var.md'
    - Filter: 'linux/filter.md'
    - Path: 'linux/path.md'
    - Permission: 'linux/permission.md'
    - File System: 'linux/file_system.md'
    - Services: 'linux/services.md'
    - User: 'linux/user.md'
    - Vim: 'linux/vim.md'
    - GUI: 'linux/GUI.md'
    - Distros: 'linux/distros.md'
    - Boot: 'linux/boot.md'
    - Kernel: 'linux/kernel.md'

  - Git:
    - INFO: git/index.md
    - Clone:
      - HTTP: git/clone/http.md
      - SSH: git/clone/ssh.md
      - Swap HTTP <-> SSH: git/clone/swap_http_ssh.md
    - Commands:
      - Bisect: 'git/commands/bisect.md'
      - Branch: 'git/commands/branch.md'
      - Checkout: 'git/commands/checkout.md'
      - Default Commands: 'git/commands/default_commands.md'
      - Diff: 'git/commands/diff.md'
      - Log: 'git/commands/log.md'
      - Status ui: 'git/commands/status_ui.md'
      - Remote Repository: 'git/commands/remote_repository.md'
      - Stash: 'git/commands/stash.md'
    - Concepts:
      - Checkout vs Cherrypick: 'git/concepts/checkout_vs_cherrypick.md'
      - Git config: 'git/concepts/git-config.md'
      - Merge vs Rebase: 'git/concepts/merge_vs_rebase.md'

  - Networking:
    - INFO: networking/index.md
    - OSI: 'networking/OSI.md'
    - IP: 'networking/ip.md'
    - Linux Commands: 'networking/linux_commands.md'

  - Kubernetes:
    - INFO: kubernetes/index.md
    - Getting Started:
        - History: kubernetes/history.md
        - Introduction: kubernetes/introduction.md
    - Setup:
        - Setup Kubectl: kubernetes/setup_kubectl.md
        - Setup Minikube: kubernetes/setup_minikube.md
        - Setup Kops: kubernetes/setup_kops.md
    - Concepts:
        - Kubernetes architecture diagram: kubernetes/kubernetes_infrastructure_diagram.md
        - Commands & Arguments: kubernetes/commands_arguments.md
        - Objects: kubernetes/objects.md
        - Namespace: kubernetes/namespaces.md
        - Kube Config: kubernetes/kube_config.md
        - Jobs and Cron Jobs: kubernetes/jobs_cron_jobs.md
        - DaemonSet: kubernetes/daemonset.md
        - Taints and Tolerations: kubernetes/taints_tolerations.md
        - Limits: kubernetes/limits.md
    - Workloads:
        - ReplicaSet: kubernetes/replicaset.md
        - Deployment: kubernetes/deployment.md
        - Service: kubernetes/service.md
        - Volume: kubernetes/volumes.md
        - Config Map: kubernetes/config_map.md
        - Secrets: kubernetes/secrets.md
        - ingress: kubernetes/ingress.md
    - Helm:
        - Introduction: kubernetes/helm_introduction.md
        - Hands On: kubernetes/helm_hands_on.md
        - Helm with AI: kubernetes/helm_with_ai.md
    - EKS: kubernetes/eks_introduction.md
    - Logging:
        - Different Logging: kubernetes/different_logging.md
        - Lens: kubernetes/lens.md
    - Cheat Sheet: kubernetes/cheatsheet.md

  - Agile:
    - INFO: agile/index.md
    - Fundamentals:
      - Introduction: agile/fundamentals/introduction.md
      - Agile Principles: agile/fundamentals/principles.md
      - Scrum Framework: agile/fundamentals/scrum-framework.md
      - Agile vs DevOps: agile/fundamentals/agile-vs-devops.md
  
  - AI:
    - INFO: ai/index.md
    - Fundamentals:
      - AI: ai/fundamentals/ai.md
      - General AI: ai/fundamentals/general_ai.md
      - Generative AI: ai/fundamentals/generative_ai.md
      - Hallucinations: ai/fundamentals/hallucinations.md
      - Machine Learning: ai/fundamentals/machine_learning.md
      - Narrow AI: ai/fundamentals/narrow_ai.md
      - Prompt: ai/fundamentals/prompt.md
      - Super AI: ai/fundamentals/super_ai.md
    - Copilot:
      - CLI: ai/copilot/cli.md
      - Process Flow: ai/copilot/process_flow.md 